import { useEffect, useId, useRef, useState } from "react";
import { announce } from "../lib/announce";
const SPEEDS=[0.75,1,1.25,1.5,2];
export default function VideoPlayer({ src, storageKey, onEnded, poster, subtitles=[], transcript="", title="Dars videosi" }) {
  const videoRef=useRef(null); const transcriptId=useId(); const [speed,setSpeed]=useState(1); const [showTranscript,setShowTranscript]=useState(false);
  useEffect(()=>{const video=videoRef.current;if(!video||!storageKey)return;const saved=Number(localStorage.getItem(storageKey));const loaded=()=>{if(saved&&saved<video.duration-5)video.currentTime=saved};video.addEventListener("loadedmetadata",loaded);return()=>video.removeEventListener("loadedmetadata",loaded)},[src,storageKey]);
  useEffect(()=>{const video=videoRef.current;if(!video)return;const time=()=>{if(storageKey&&video.currentTime>0)localStorage.setItem(storageKey,String(Math.floor(video.currentTime)))};const key=event=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;if(event.key===" "){event.preventDefault();video.paused?video.play():video.pause()}if(event.key==="ArrowRight")video.currentTime=Math.min(video.duration||Infinity,video.currentTime+10);if(event.key==="ArrowLeft")video.currentTime=Math.max(0,video.currentTime-10);if(event.key.toLowerCase()==="c"&&subtitles.length){const track=video.textTracks[0];track.mode=track.mode==="showing"?"hidden":"showing";announce(track.mode==="showing"?"Subtitr yoqildi":"Subtitr o‘chirildi")}};video.addEventListener("timeupdate",time);window.addEventListener("keydown",key);return()=>{video.removeEventListener("timeupdate",time);window.removeEventListener("keydown",key)}},[storageKey,subtitles.length]);
  if(!src)return <div role="status" className="video-locked">Bu dars qulflangan, ko‘rish uchun kursga yoziling.</div>;
  const change=next=>{setSpeed(next);videoRef.current.playbackRate=next;announce(`Video tezligi ${next}x`)};
  return <section className="accessible-video" aria-label={title}><video ref={videoRef} src={src} poster={poster} controls preload="metadata" onEnded={onEnded} aria-describedby={transcript ? transcriptId : undefined}>{subtitles.map(track=><track key={`${track.srclang}-${track.src}`} kind="subtitles" src={track.src} srcLang={track.srclang} label={track.label} default={track.default}/>)}Brauzeringiz video elementini qo‘llamaydi.</video><div className="video-tools"><fieldset><legend>Tezlik</legend>{SPEEDS.map(item=><button type="button" key={item} aria-pressed={speed===item} onClick={()=>change(item)}>{item}x</button>)}</fieldset>{transcript&&<button type="button" aria-expanded={showTranscript} aria-controls={transcriptId} onClick={()=>setShowTranscript(value=>!value)}>{showTranscript?"Transkriptni yopish":"Transkriptni ochish"}</button>}</div>{transcript&&<div id={transcriptId} hidden={!showTranscript} className="video-transcript"><h3>Transkript</h3><p>{transcript}</p></div>}<p className="sr-only">Klaviatura: Space pauza, chap va o‘ng strelka 10 soniya, C subtitr.</p></section>;
}
