import { useEffect, useId, useRef, useState } from "react";
import { announce } from "../lib/announce";
import { mediaApi } from "../lib/api";
import "./VideoPlayer.css";
const SPEEDS=[0.75,1,1.25,1.5,2];
export default function VideoPlayer({ src, lessonId, token, storageKey, onEnded, poster, subtitles=[], transcript="", title="Dars videosi" }){
 const videoRef=useRef(null);const transcriptId=useId();const [manifest,setManifest]=useState(null);const [selected,setSelected]=useState(0);const [speed,setSpeed]=useState(1);const [showTranscript,setShowTranscript]=useState(false);const [error,setError]=useState("");const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;if(!lessonId||!token){setManifest(null);return;}setError("");mediaApi.signLesson(lessonId,token).then(data=>{if(active){setManifest(data);setSelected(0)}}).catch(reason=>active&&setError(reason.message));return()=>{active=false}},[lessonId,token,retry]);
 const sources=manifest?.sources||[];const preferred=manifest?.preferred_source;const activeSource=sources[selected]||preferred||{url:src,type:"video/mp4",label:"Auto"};
 useEffect(()=>{const video=videoRef.current;if(!video)return;const resume=Number(manifest?.resume_seconds||localStorage.getItem(storageKey)||0);const loaded=()=>{if(resume&&resume<video.duration-5)video.currentTime=resume};video.addEventListener("loadedmetadata",loaded);return()=>video.removeEventListener("loadedmetadata",loaded)},[activeSource.url,manifest?.resume_seconds,storageKey]);
 useEffect(()=>{const video=videoRef.current;if(!video)return;let lastSaved=0;const save=()=>{const position=Math.floor(video.currentTime||0);if(storageKey&&position)localStorage.setItem(storageKey,String(position));if(lessonId&&token&&position-lastSaved>=10){lastSaved=position;mediaApi.saveProgress(lessonId,{position_seconds:position,duration_seconds:Math.floor(video.duration||0)},token).catch(()=>{})}};const key=e=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;if(e.key===" "){e.preventDefault();video.paused?video.play():video.pause()}if(e.key==="ArrowRight")video.currentTime=Math.min(video.duration||Infinity,video.currentTime+10);if(e.key==="ArrowLeft")video.currentTime=Math.max(0,video.currentTime-10);if(e.key.toLowerCase()==="c"&&video.textTracks[0])video.textTracks[0].mode=video.textTracks[0].mode==="showing"?"hidden":"showing"};video.addEventListener("timeupdate",save);window.addEventListener("keydown",key);return()=>{video.removeEventListener("timeupdate",save);window.removeEventListener("keydown",key)}},[lessonId,storageKey,token,activeSource.url]);
 if(error)return <div role="alert">Video yuklanmadi. <button onClick={()=>setRetry(v=>v+1)}>Qayta urinish</button></div>;if(!activeSource.url)return <p>Bu dars qulflangan, ko‘rish uchun kursga yoziling.</p>;
 const changeSpeed=next=>{setSpeed(next);videoRef.current.playbackRate=next;announce(`Video tezligi ${next}x`)};const pip=()=>videoRef.current?.requestPictureInPicture?.();const fullscreen=()=>videoRef.current?.requestFullscreen?.();
 return <section className="video-player"><video key={activeSource.url} ref={videoRef} controls playsInline preload="metadata" poster={poster} onEnded={onEnded} aria-label={title} onError={()=>setError("Video manbasi ishlamadi")}><source src={activeSource.url} type={activeSource.type}/>{(manifest?.subtitles||subtitles).map(track=><track key={track.src||track.url} kind="captions" src={track.src||track.url} srcLang={track.srclang||track.lang||"uz"} label={track.label||"Subtitr"}/>)}Brauzeringiz video elementini qo‘llamaydi.</video>{sources.length>1&&<label>Sifat<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{sources.map((source,index)=><option key={source.url} value={index}>{source.label||source.delivery||`Manba ${index+1}`}</option>)}</select></label>}<div className="video-player__controls"><span>Tezlik</span>{SPEEDS.map(item=><button key={item} onClick={()=>changeSpeed(item)} aria-pressed={speed===item}>{item}x</button>)}<button onClick={pip}>Picture in Picture</button><button onClick={fullscreen}>To‘liq ekran</button>{transcript&&<button aria-expanded={showTranscript} aria-controls={transcriptId} onClick={()=>setShowTranscript(v=>!v)}>{showTranscript?"Transkriptni yopish":"Transkriptni ochish"}</button>}</div>{transcript&&<div id={transcriptId} hidden={!showTranscript}><h3>Transkript</h3><p>{transcript}</p></div>}</section>;
}
