import { useCallback, useEffect, useMemo, useState } from "react";
import AdminWorkspaceShell from "../components/AdminWorkspaceShell";
import { useAuth } from "../context/AuthContext";
import { request } from "../lib/request";
const ROLES = ["user", "instructor", "admin", "superadmin"];
export default function AdminUsersPage() {
  const { token, user } = useAuth(); const isSuperadmin = user?.role === "superadmin"; const [users,setUsers]=useState([]); const [meta,setMeta]=useState({page:1,pages:1,total:0}); const [query,setQuery]=useState(""); const [role,setRole]=useState("all"); const [status,setStatus]=useState("all"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(null);
  const load=useCallback(async(page=1)=>{setLoading(true);setError("");try{const params=new URLSearchParams({page,per_page:25,q:query,role,status});const result=await request(`${isSuperadmin?"/api/superadmin/users":"/api/admin/users"}?${params}`,{token});setUsers(result.items??result);setMeta(result.items?result:{page:1,pages:1,total:result.length});}catch(err){setError(err.message)}finally{setLoading(false)}},[isSuperadmin,token,query,role,status]);
  useEffect(()=>{load(1)},[load]);
  async function updateUser(id,patch){setBusy(id);try{await request(`/api/superadmin/users/${id}/${patch.role?"role":"status"}`,{method:"PATCH",body:JSON.stringify(patch),token});await load(meta.page)}catch(err){setError(err.message)}finally{setBusy(null)}}
  return <AdminWorkspaceShell superadmin={isSuperadmin}><header className="admin-page-head"><div><div className="admin-kicker">Access control</div><h1>Users & permissions</h1><p>{isSuperadmin?"Rollarni va account holatini boshqaring.":"Platforma foydalanuvchilarini ko'ring."}</p></div><div className="admin-actions"><span className="admin-btn">{meta.total} ta natija</span></div></header><section className="admin-section"><div className="admin-user-filters"><input aria-label="User qidirish" placeholder="Ism yoki email qidirish" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Rol bo'yicha filter" value={role} onChange={e=>setRole(e.target.value)}><option value="all">Barcha rollar</option>{ROLES.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Holat bo'yicha filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Barcha holatlar</option><option value="active">Faol</option><option value="inactive">Bloklangan</option></select></div>{error&&<div className="admin-inline-error">{error}</div>}{loading?<p>Foydalanuvchilar yuklanmoqda...</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Qo'shilgan</th></tr></thead><tbody>{users.map(item=>{const locked=!isSuperadmin||item.id===user?.id||busy===item.id;return <tr key={item.id}><td><strong>{item.name||"Nomsiz user"}</strong><br/><small>{item.email}</small></td><td>{isSuperadmin?<select value={item.role} disabled={locked} onChange={e=>updateUser(item.id,{role:e.target.value})}>{ROLES.map(value=><option key={value}>{value}</option>)}</select>:<span className="admin-role-pill">{item.role}</span>}</td><td>{isSuperadmin?<label className="admin-status-toggle"><input type="checkbox" checked={Boolean(item.is_active)} disabled={locked} onChange={e=>updateUser(item.id,{is_active:e.target.checked})}/>{item.is_active?"Faol":"Bloklangan"}</label>:<span>{item.is_active?"Faol":"Bloklangan"}</span>}</td><td><small>{item.created_at?new Date(item.created_at).toLocaleDateString("uz-UZ"):"-"}</small></td></tr>})}</tbody></table><div className="admin-actions"><button className="admin-btn" disabled={meta.page<=1} onClick={()=>load(meta.page-1)}>Oldingi</button><span>{meta.page} / {meta.pages}</span><button className="admin-btn" disabled={meta.page>=meta.pages} onClick={()=>load(meta.page+1)}>Keyingi</button></div>{!users.length&&<p className="admin-empty">Filter bo'yicha user topilmadi.</p>}</div>}</section></AdminWorkspaceShell>;
}
