import { useCallback, useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { moderationApi } from "../lib/moderationApi";
import "./ModerationPage.css";

const typeLabel = { forum_thread: "Forum mavzusi", forum_post: "Forum javobi", review: "Sharh" };
export default function ModerationPage() {
  const { token } = useAuth(); const [queue, setQueue] = useState([]); const [appeals, setAppeals] = useState([]); const [active, setActive] = useState(null); const [reason, setReason] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [reports, appealRows] = await Promise.all([moderationApi.queue(token), moderationApi.appeals(token)]); setQueue(reports.results || []); setAppeals(appealRows || []); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  const act = async (action) => { if (!active || reason.trim().length < 3) return setError("Qaror sababi kamida 3 belgi bo‘lsin"); try { await moderationApi.act(token, active.id, { action, reason, internal_note: note || null }); setActive(null); setReason(""); setNote(""); await load(); } catch (e) { setError(e.message); } };
  const decide = async (id, status) => { const decision = window.prompt(status === "approved" ? "Tiklash sababi" : "Rad etish sababi"); if (!decision) return; await moderationApi.decide(token, id, { status, decision_note: decision }); await load(); };
  if (loading) return <main className="mod-shell" aria-busy="true"><div className="mod-skeleton" /><div className="mod-skeleton tall" /></main>;
  return <main className="mod-shell"><header><p>TRUST & SAFETY</p><h1>Moderation navbati</h1><button type="button" onClick={load}>Yangilash</button></header>{error && <div className="mod-error" role="alert">{error}</div>}<div className="mod-layout"><section><div className="mod-heading"><h2>Ochiq reportlar</h2><span>{queue.length}</span></div>{queue.length ? <ol className="mod-list">{queue.map((row) => <li key={row.id} className={active?.id === row.id ? "active" : ""}><button type="button" onClick={() => setActive(row)}><span>{typeLabel[row.content_type] || row.content_type} #{row.content_id}</span><strong>{row.reason}</strong><small>{row.details || "Qo‘shimcha izoh yo‘q"}</small></button></li>)}</ol> : <p className="mod-empty">Navbat bo‘sh. Hamjamiyat tinch.</p>}</section><aside><h2>Qaror</h2>{active ? <><p><strong>{active.reason}</strong></p><label>Sabab<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><label>Ichki note<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><div className="mod-actions"><button onClick={() => act("dismiss")}>Rad etish</button><button onClick={() => act("hide")}>Yashirish</button><button onClick={() => act("suspend")}>Suspend</button><button className="danger" onClick={() => act("ban")}>Ban</button></div></> : <p>Qaror chiqarish uchun reportni tanlang.</p>}</aside></div><section className="mod-appeals"><div className="mod-heading"><h2>Appeal’lar</h2><span>{appeals.length}</span></div>{appeals.map((row) => <article key={row.id}><div><strong>Action #{row.action_id}</strong><p>{row.statement}</p></div><div><button onClick={() => decide(row.id, "approved")}>Qabul qilish</button><button onClick={() => decide(row.id, "rejected")}>Rad etish</button></div></article>)}</section></main>;
}
