import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { formatPrice } from "../lib/api";
import { supportApi } from "../lib/supportApi";
import "./SupportConsolePage.css";

const stamp = (value) => value ? new Date(value).toLocaleString("uz-UZ", { dateStyle: "medium", timeStyle: "short" }) : "";
export default function SupportConsolePage() {
  const { token } = useAuth(); const [query, setQuery] = useState(""); const [results, setResults] = useState([]); const [data, setData] = useState(null); const [tab, setTab] = useState("timeline"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const search = async (event) => { event.preventDefault(); if (query.trim().length < 2) return; setLoading(true); setError(""); try { setResults(await supportApi.search(token, query)); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const open = async (id) => { setLoading(true); setError(""); try { setData(await supportApi.workspace(token, id)); setResults([]); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const regenerate = async (id) => { try { await supportApi.regenerate(token, data.user.id, id); await open(data.user.id); } catch (e) { setError(e.message); } };
  const resend = async (id) => { try { await supportApi.resend(token, data.user.id, id); await open(data.user.id); } catch (e) { setError(e.message); } };
  return <main className="support-shell"><header><p>SUPPORT WORKSPACE</p><h1>User holatini tushunish, akkauntga kirmasdan.</h1><form onSubmit={search}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Email yoki ism" aria-label="Foydalanuvchini qidirish"/><button disabled={loading}>Qidirish</button></form></header>{error && <div className="support-error" role="alert">{error}</div>}{results.length > 0 && <ol className="support-results">{results.map((row) => <li key={row.id}><button onClick={() => open(row.id)}><strong>{row.name || "Nomsiz"}</strong><span>{row.email}</span><small>{row.is_active ? "Faol" : "Suspended"}</small></button></li>)}</ol>}{loading && <div className="support-loading">Ma’lumotlar yig‘ilmoqda...</div>}{data && <><section className="support-profile"><div><span className={data.user.is_active ? "status on" : "status off"}>{data.user.is_active ? "Faol" : "Suspended"}</span><h2>{data.user.name || data.user.email}</h2><p>{data.user.email} · {data.user.role}</p></div><aside><strong>Read-only support view</strong><p>{data.safe_view.notice}</p></aside></section><nav className="support-tabs" aria-label="Support bo‘limlari">{["timeline","enrollments","payments","certificates","notifications"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav><section className="support-panel">{tab === "timeline" && <ol className="timeline">{data.timeline.map((row, i) => <li key={`${row.type}-${i}`}><span>{row.type}</span><div><strong>{row.label}</strong><small>{stamp(row.at)}</small></div></li>)}</ol>}{tab === "enrollments" && <table><thead><tr><th>Kurs</th><th>Progress</th><th>Holat</th></tr></thead><tbody>{data.enrollments.map((row) => <tr key={row.id}><td>{row.course_title || row.course_id}</td><td>{row.progress}%</td><td>{row.completed_at ? "Yakunlangan" : "Faol"}</td></tr>)}</tbody></table>}{tab === "payments" && <table><thead><tr><th>Order</th><th>Kurs</th><th>Summa</th><th>Holat</th></tr></thead><tbody>{data.orders.map((row) => <tr key={row.id}><td>#{row.id}</td><td>{row.course_title || row.course_id}</td><td>{formatPrice(row.amount)}</td><td>{row.status}{row.failure_reason ? `: ${row.failure_reason}` : ""}</td></tr>)}</tbody></table>}{tab === "certificates" && <ul className="support-actions">{data.certificates.map((row) => <li key={row.id}><div><strong>{row.title}</strong><small>{row.serial}</small></div><button onClick={() => regenerate(row.id)}>PDF qayta yaratish</button></li>)}</ul>}{tab === "notifications" && <ul className="support-actions">{data.notifications.map((row) => <li key={row.id}><div><strong>{row.message}</strong><small>{stamp(row.created_at)}</small></div><button onClick={() => resend(row.id)}>Qayta yuborish</button></li>)}</ul>}</section></>}</main>;
}
