const API_URL = import.meta.env.VITE_API_URL ?? "http://127.0.0.1:8000";
const TOKEN_KEY = "designora-auth-token";
function extractErrorMessage(payload) { const detail=payload?.detail; if(!detail)return "So'rovni bajarib bo'lmadi."; if(typeof detail==="string")return detail; if(Array.isArray(detail))return detail.map((item)=>item?.msg??"Noma'lum xato").join(" "); return "So'rovni bajarib bo'lmadi."; }
let refreshPromise=null;
async function refreshAccessToken(){if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{const res=await fetch(`${API_URL}/api/auth/refresh`,{method:"POST",credentials:"include"});if(!res.ok)throw new Error("refresh failed");const data=await res.json();const newToken=data?.access_token;if(newToken){localStorage.setItem(TOKEN_KEY,newToken);window.dispatchEvent(new CustomEvent("designora-token-refreshed",{detail:newToken}));}return newToken;})().finally(()=>{refreshPromise=null;});return refreshPromise;}
function invalidateClientSession(){localStorage.removeItem(TOKEN_KEY);window.dispatchEvent(new CustomEvent("designora-session-invalidated"));}
async function request(path,options={}){const{token,headers,_retry,...rest}=options;const response=await fetch(`${API_URL}${path}`,{...rest,credentials:"include",headers:{"Content-Type":"application/json",...(headers??{}),...(token?{Authorization:`Bearer ${token}`}:{})}});if(response.status===401&&token&&!_retry&&!path.startsWith("/api/auth/")){try{const next=await refreshAccessToken();if(next)return request(path,{...options,token:next,_retry:true});}catch{/* preserve response */}}const contentType=response.headers.get("content-type")??"";const payload=contentType.includes("application/json")?await response.json():null;if(response.status===403&&token){invalidateClientSession();}if(!response.ok)throw new Error(extractErrorMessage(payload));return payload;}
function withQuery(path,params={}){const usp=new URLSearchParams();Object.entries(params).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=="")usp.append(key,value);});const qs=usp.toString();return qs?`${path}?${qs}`:path;}
export const authApi={login:(body)=>request("/api/auth/login",{method:"POST",body:JSON.stringify(body)}),register:(body)=>request("/api/auth/register",{method:"POST",body:JSON.stringify(body)}),profile:(token)=>request("/api/profile/me",{method:"GET",token}),dashboard:async(token)=>{const s=await request("/api/profile/stats",{method:"GET",token});return{...(s??{}),metrics:[{label:"Yozilgan kurslar",value:s?.courses_enrolled??0},{label:"Tugatilgan",value:s?.courses_completed??0},{label:"O'rganilgan soat",value:s?.hours_learned??0},{label:"Sertifikatlar",value:s?.certificates??0},{label:"Ball",value:s?.points??0},{label:"Streak (kun)",value:s?.streak_days??0}];},courses:()=>request("/api/courses",{method:"GET"}),issueRefresh:(token)=>request("/api/auth/issue-refresh",{method:"POST",token}),refresh:()=>request("/api/auth/refresh",{method:"POST"}),logoutAll:(token)=>request("/api/auth/logout-all",{method:"POST",token})};
export const coursesApi={list:()=>request("/api/courses"),detail:(courseId)=>request(`/api/courses/${courseId}/detail`)};
export const learningApi={enroll:(courseId,token)=>request(`/api/learning/enroll/${courseId}`,{method:"POST",token}),unenroll:(courseId,token)=>request(`/api/learning/enroll/${courseId}`,{method:"DELETE",token}),myCourses:(token)=>request("/api/learning/my-courses",{token}),learn:(courseId,token)=>request(`/api/learning/courses/${courseId}`,{token}),completeLesson:(lessonId,token)=>request(`/api/learning/lessons/${lessonId}/complete`,{method:"POST",token}),uncompleteLesson:(lessonId,token)=>request(`/api/learning/lessons/${lessonId}/uncomplete`,{method:"POST",token})};
export const analyticsApi={admin:(token)=>request("/api/analytics/admin",{token}),instructor:(token)=>request("/api/analytics/instructor",{token}),track:(body,token)=>request("/api/analytics/track",{method:"POST",body:JSON.stringify(body),token})};
export const notificationsApi={list:(token,onlyUnread=false)=>request(withQuery("/api/notifications",{only_unread:onlyUnread}),{token}),unreadCount:(token)=>request("/api/notifications/unread-count",{token}),markRead:(id,token)=>request(`/api/notifications/${id}/read`,{method:"POST",token}),markAllRead:(token)=>request("/api/notifications/read-all",{method:"POST",token}),remove:(id,token)=>request(`/api/notifications/${id}`,{method:"DELETE",token})};
export function formatPrice(price){const p=Number(price)||0;return p<=0?"Bepul":`${p.toLocaleString("uz-UZ")} so'm`;}
