const API_URL = import.meta.env.VITE_API_URL ?? "http://127.0.0.1:8000";

// AuthContext token'ni shu kalitda saqlaydi (ikkovi bir xil bo'lishi shart).
const TOKEN_KEY = "designora-auth-token";

function extractErrorMessage(payload) { const detail = payload?.detail; if (!detail) return "So'rovni bajarib bo'lmadi."; if (typeof detail === "string") return detail; if (Array.isArray(detail)) return detail.map((item) => item?.msg ?? "Noma'lum xato").join(" "); return "So'rovni bajarib bo'lmadi."; }
let refreshPromise = null;
async function refreshAccessToken() { if (refreshPromise) return refreshPromise; refreshPromise = (async () => { const res = await fetch(`${API_URL}/api/auth/refresh`, { method: "POST", credentials: "include" }); if (!res.ok) throw new Error("refresh failed"); const data = await res.json(); const newToken = data?.access_token; if (newToken) { try { localStorage.setItem(TOKEN_KEY, newToken); window.dispatchEvent(new CustomEvent("designora-token-refreshed", { detail: newToken })); } catch {} } return newToken; })().finally(() => { refreshPromise = null; }); return refreshPromise; }
async function request(path, options = {}) { const { token, headers, _retry, ...rest } = options; const response = await fetch(`${API_URL}${path}`, { ...rest, credentials: "include", headers: { "Content-Type": "application/json", ...(headers ?? {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); if (response.status === 401 && !_retry && token && !path.startsWith("/api/auth/")) { try { const newToken = await refreshAccessToken(); if (newToken) return request(path, { ...options, token: newToken, _retry: true }); } catch {} } const contentType = response.headers.get("content-type") ?? ""; const payload = contentType.includes("application/json") ? await response.json() : null; if (!response.ok) throw new Error(extractErrorMessage(payload)); return payload; }
function withQuery(path, params = {}) { const usp = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== "") usp.append(key, value); }); const qs = usp.toString(); return qs ? `${path}?${qs}` : path; }

export const authApi = {
  login: (body) => request("/api/auth/login", { method: "POST", body: JSON.stringify(body) }),
  register: (body) => request("/api/auth/register", { method: "POST", body: JSON.stringify(body) }),
  profile: (token) => request("/api/profile/me", { method: "GET", token }),
  dashboard: async (token) => { const s = await request("/api/profile/stats", { method: "GET", token }); return { ...(s ?? {}), metrics: [{ label: "Yozilgan kurslar", value: s?.courses_enrolled ?? 0 }, { label: "Tugatilgan", value: s?.courses_completed ?? 0 }, { label: "O'rganilgan soat", value: s?.hours_learned ?? 0 }, { label: "Sertifikatlar", value: s?.certificates ?? 0 }, { label: "Ball", value: s?.points ?? 0 }, { label: "Streak (kun)", value: s?.streak_days ?? 0 }] }; },
  courses: () => request("/api/courses", { method: "GET" }),
  issueRefresh: (token) => request("/api/auth/issue-refresh", { method: "POST", token }),
  refresh: () => request("/api/auth/refresh", { method: "POST" }),
  logoutAll: (token) => request("/api/auth/logout-all", { method: "POST", token }),
};
export const coursesApi = { list: () => request("/api/courses"), detail: (courseId) => request(`/api/courses/${courseId}/detail`) };
export const learningApi = { enroll: (courseId, token) => request(`/api/learning/enroll/${courseId}`, { method: "POST", token }), unenroll: (courseId, token) => request(`/api/learning/enroll/${courseId}`, { method: "DELETE", token }), myCourses: (token) => request("/api/learning/my-courses", { token }), learn: (courseId, token) => request(`/api/learning/courses/${courseId}`, { token }), completeLesson: (lessonId, token) => request(`/api/learning/lessons/${lessonId}/complete`, { method: "POST", token }), uncompleteLesson: (lessonId, token) => request(`/api/learning/lessons/${lessonId}/uncomplete`, { method: "POST", token }) };
export const discoveryApi = { search: (params = {}) => request(withQuery("/api/discovery/search", params)), filters: () => request("/api/discovery/filters"), categories: () => request("/api/discovery/categories"), bestselling: (limit = 6) => request(withQuery("/api/discovery/recommendations/bestselling", { limit })), similar: (courseId, limit = 6) => request(withQuery(`/api/discovery/recommendations/similar/${courseId}`, { limit })) };
export const quizApi = { courseQuizzes: (courseId, token) => request(`/api/quiz/courses/${courseId}/quizzes`, { token }), take: (quizId, token) => request(`/api/quiz/quizzes/${quizId}`, { token }), submit: (quizId, answers, token) => request(`/api/quiz/quizzes/${quizId}/submit`, { method: "POST", body: JSON.stringify({ answers }), token }) };
export const reviewsApi = { summary: (courseId) => request(`/api/reviews/courses/${courseId}/summary`), list: (courseId) => request(`/api/reviews/courses/${courseId}`), upsert: (courseId, body, token) => request(`/api/reviews/courses/${courseId}`, { method: "POST", body: JSON.stringify(body), token }), remove: (reviewId, token) => request(`/api/reviews/${reviewId}`, { method: "DELETE", token }) };
export const qaApi = { list: (lessonId, token) => request(`/api/qa/lessons/${lessonId}/questions`, { token }), ask: (lessonId, body, token) => request(`/api/qa/lessons/${lessonId}/questions`, { method: "POST", body: JSON.stringify(body), token }), answer: (questionId, body, token) => request(`/api/qa/questions/${questionId}/answers`, { method: "POST", body: JSON.stringify(body), token }), resolve: (questionId, token) => request(`/api/qa/questions/${questionId}/resolve`, { method: "PATCH", token }) };
export const notesApi = { forLesson: (lessonId, token) => request(`/api/notes/lessons/${lessonId}`, { token }), create: (lessonId, body, token) => request(`/api/notes/lessons/${lessonId}`, { method: "POST", body: JSON.stringify(body), token }), update: (noteId, body, token) => request(`/api/notes/${noteId}`, { method: "PATCH", body: JSON.stringify(body), token }), remove: (noteId, token) => request(`/api/notes/${noteId}`, { method: "DELETE", token }) };
export const certificatesApi = { mine: (token) => request("/api/certificates/my", { token }), issue: (courseId, token) => request(`/api/certificates/courses/${courseId}/issue`, { method: "POST", token }), download: (certId, token) => request(`/api/certificates/${certId}/download`, { token }), verify: (code) => request(`/api/certificates/verify/${code}`) };
export const mediaApi = { signLesson: (lessonId, token) => request(`/api/media/lessons/${lessonId}/sign`, { method: "POST", token }) };
export const paymentsApi = { checkout: (body, token) => request("/api/payments/checkout", { method: "POST", body: JSON.stringify(body), token }), orderStatus: (orderId, token) => request(`/api/payments/orders/${orderId}`, { token }) };
export const notificationsApi = { list: (token, onlyUnread = false) => request(withQuery("/api/notifications", { only_unread: onlyUnread }), { token }), unreadCount: (token) => request("/api/notifications/unread-count", { token }), markRead: (id, token) => request(`/api/notifications/${id}/read`, { method: "POST", token }), markAllRead: (token) => request("/api/notifications/read-all", { method: "POST", token }), remove: (id, token) => request(`/api/notifications/${id}`, { method: "DELETE", token }) };
export const blogApi = { list: (params = {}) => request(withQuery("/api/blog", params)), getBySlug: (slug) => request(`/api/blog/${slug}`) };
export const forumApi = { listThreads: (params = {}) => request(withQuery("/api/forum/threads", params)), getThread: (threadId) => request(`/api/forum/threads/${threadId}`), createThread: (body, token) => request("/api/forum/threads", { method: "POST", body: JSON.stringify(body), token }), reply: (threadId, body, token) => request(`/api/forum/threads/${threadId}/posts`, { method: "POST", body: JSON.stringify(body), token }) };
export const referralApi = { myCode: (token) => request("/api/referrals/my-code", { token }), apply: (code, token) => request("/api/referrals/apply", { method: "POST", body: JSON.stringify({ code }), token }), myReferrals: (token) => request("/api/referrals/my-referrals", { token }) };
export const instructorsApi = { get: (instructorId) => request(`/api/instructors/${instructorId}`), courses: (instructorId) => request(`/api/instructors/${instructorId}/courses`) };
export const gamificationApi = { me: (token) => request("/api/gamification/me", { token }), badges: (token) => request("/api/gamification/badges", { token }), leaderboard: (limit = 20) => request(withQuery("/api/gamification/leaderboard", { limit })) };
export const analyticsApi = { instructor: (token) => request("/api/analytics/instructor", { token }), admin: (token) => request("/api/analytics/admin", { token }), track: (body, token) => request("/api/analytics/track", { method: "POST", body: JSON.stringify(body), token }) };
export const instructorApi = { listCourses: (token) => request("/api/instructor/courses", { token }), getCourse: (courseId, token) => request(`/api/instructor/courses/${courseId}`, { token }), createCourse: (body, token) => request("/api/instructor/courses", { method: "POST", body: JSON.stringify(body), token }), updateCourse: (courseId, body, token) => request(`/api/instructor/courses/${courseId}`, { method: "PATCH", body: JSON.stringify(body), token }), publishCourse: (courseId, token) => request(`/api/instructor/courses/${courseId}/publish`, { method: "POST", token }), unpublishCourse: (courseId, token) => request(`/api/instructor/courses/${courseId}/unpublish`, { method: "POST", token }), createModule: (courseId, body, token) => request(`/api/instructor/courses/${courseId}/modules`, { method: "POST", body: JSON.stringify(body), token }), updateModule: (moduleId, body, token) => request(`/api/instructor/modules/${moduleId}`, { method: "PATCH", body: JSON.stringify(body), token }), deleteModule: (moduleId, token) => request(`/api/instructor/modules/${moduleId}`, { method: "DELETE", token }), createLesson: (courseId, body, token) => request(`/api/instructor/courses/${courseId}/lessons`, { method: "POST", body: JSON.stringify(body), token }), updateLesson: (lessonId, body, token) => request(`/api/instructor/lessons/${lessonId}`, { method: "PATCH", body: JSON.stringify(body), token }), deleteLesson: (lessonId, token) => request(`/api/instructor/lessons/${lessonId}`, { method: "DELETE", token }) };
export function formatDuration(totalMinutes) { const mins = Number(totalMinutes) || 0; if (mins < 60) return `${mins} daqiqa`; const hours = Math.floor(mins / 60); const rem = mins % 60; return rem ? `${hours} soat ${rem} daq` : `${hours} soat`; }
export function formatSeconds(totalSeconds) { const s = Math.max(0, Math.floor(Number(totalSeconds) || 0)); const m = Math.floor(s / 60); const sec = s % 60; return `${m}:${sec.toString().padStart(2, "0")}`; }
export function formatPrice(price) { const p = Number(price) || 0; if (p <= 0) return "Bepul"; return `${p.toLocaleString("uz-UZ")} so'm`; }
